apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieproject
  template:
    metadata:
      labels:
        app: movieproject
    spec:
      containers:
        - name: myapp
          image: robinhosz/movieproject:2.0
          ports:
            - containerPort: 8080
